version: '3.7'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=playlist-backup
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=playlist-backup

volumes:
    postgres:
